# Plain HTTP listener port
listen_port: 8000

# Optional TLS listener port. If >0, the plain listener port will redirect to
# the TLS listener port and the server will automatically get a certificate
# from Let's Encrypt for the domain in tls_domain.
tls_listen_port: 8443
tls_domain: my1403.example.com

# Path to database file to store application data.
database_file: virtual1403.db

# Initial admin email address. If this account does not exist at server
# startup, it will be created as an admin with a random password that is
# printed in the log.
create_admin: admin@example.com

# font_file is an optional font file to use
#font_file: font.ttf

# server_base_url is the base URL for this server, without any trailing slashes
# e.g.: https://my.server.com
server_base_url: https://localhost:4444/

mail_config:
  from_address: virtual.1403@example.com
  server: smtp.example.com
  port: 587
  username: virtual.1403
  password: asdf1234
