listen_port: 4444
database_file: virtual1403.db
create_admin: admin@example.com

# font_file is an optional font file to use
#font_file: font.ttf

# server_base_url is the base URL for this server, without any trailing slashes
# e.g.:
# https://my.server.com
server_base_url: https://localhost:4444/print

mail_config:
  from_address: virtual.1403@example.com
  server: smtp.example.com
  port: 587
  username: virtual.1403
  password: asdf1234
