# Plain HTTP listener port
listen_port: 8000

# Optional TLS listener port. If >0, the plain listener port will redirect to
# the TLS listener port and the server will automatically get a certificate
# from Let's Encrypt for the domain in tls_domain.
tls_listen_port: 8443
tls_domain: my1403.example.com

# server_base_url is the base URL for this server, without any trailing slashes
# e.g.: https://my.server.com
server_base_url: https://localhost:8443/

# Path to database file to store application data.
database_file: virtual1403.db

# Initial admin email address. If this account does not exist at server
# startup, it will be created as an admin with a random password that is
# printed in the log.
create_admin: admin@example.com

# The following email address will be provided to authenticated users in page
# footers to contact server admin.
server_admin_email: admin@example.com

# font_file is an optional font file to use
#font_file: font.ttf

# Quota - jobs and page count a user is allowed during the quota period.
# Period is in hours. Values <= 0 disable the job and/or page quota.
quota_jobs: 25
quota_pages: 1000
quota_period: 24 # hours

# How many days to keep job PDFs in the database?
pdf_cleanup_days: 7

# Concurrent print jobs will limit the number of simultaneous threads running
# the print API call. The default, 0, will allow unlimited concurrency. A
# higher value will make incoming API requests to the print API block (wait)
# until a seat is available. Typically the default of 0 is fine, but you may
# need to set this due to external factors such as font license compliance,
# mail service limitations, etc.
concurrent_print_jobs: 0

# To prevent users trying to DoS the server with a huge number of overstrike
# lines (thus working around the page quota while sending the server nearly
# unlimited amounts of data), each individual job may be limited to a number
# of print directives. For a 62-lines-per-page virtual printer, a good limit
# here might be 62 * pages quota / 2, assuming users won't typically try to
# blow their entire pages quota on a single job.
max_lines_per_job: 31000

# "Nuisance jobs" are some jobs that run by default on TK4- which produce
# printouts most people don't want to be spammed with. The following is an
# array of regular expressions to identify job names that should be filtered
nuisance_job_names:
  - ^S.*_MF1$
  - ^S.*_TSO$

# The server can automatically delete inactive or unverified users.
#
# If both inactive_months_cleanup and unverified_months_cleanup are not set or
# <= 0, no auto cleanup will occur. If one is set to > 0, both must be set >
# 0.
#
# inactive_months_cleanup is the number of months after which inactive users
# will be deleted.
inactive_months_cleanup: 6
# unverified_months_cleanup is the number of months after which unverified
# accounts will be deleted.
unverified_months_cleanup: 1


# SMTP server configuration. plaintext and STARTTLS services are supported. If
# authentication isn't required, remove username and password fields.
mail_config:
  from_address: virtual.1403@example.com
  server: smtp.example.com
  port: 587
  username: virtual.1403
  password: asdf1234
