# First, we need to know how to connect to your Hercules instance. Enter the
# information for the sockdev printer device here:
hercules_address: "127.0.0.1:1403"

# mode may be "online" or "local". online sends the print job to a web
# service to render and email you a PDF. local produces the PDF locally
# and places it in the configured output directory.
mode: "online" # or "local"


### ONLINE MODE #############################################################
#
# When mode is "online", service_address and api_key are required, and should
# come from the instructions on the service's web site.
#
service_address: "https://1403.bitnet.systems/print"
access_key: "my-api-key-123"
#
#############################################################################


### LOCAL MODE ##############################################################
#
# When mode is "local", the output directory is required. Optionally, you may
# provide a font file to use in the PDFs. Leave font_file commented out to
# use the default font. The font in font_file is used for the "default"
# profiles (see below).
#
output_directory: "pdfs"
#font_file: "my-printer-font.ttf"
#
#############################################################################

### PROFILE #################################################################
#
# Profile selects the font and paper background you wish for your jobs, and
# applies to both online and local mode.
#
# Supported profiles are:
#
# default-green, default-green-noskip, default-blue, default-blue-noskip,
# default-plain, default-plain-noskip, retro-green, retro-green-noskip,
# retro-blue, retro-blue-noskip, retro-plain, retro-plain-noskip,
# modern-green, modern-green-noskip, modern-blue, modern-blue-noskip,
# modern-plain, modern-plain-noskip
#
# "default" profiles use the font specified in the config file (or, when using
# the 1403.bitnet.systems online service, 1403 Vintage Mono) or falls back to
# the default embedded IBM Plex Mono font. Only uppercase letters are used.
#
# "retro" profiles use the authentic scanned 1403 output font from
# <http://ibm-1401.info/Sched2008December.html#1403-Font>.
# This has a very limited character set, matching the standard "A" chain of
# 48 characters (but currently missing &).
#
# "modern" used IBM Plex Mono and allows lowercase letters.
#
# The "green" and "blue" variants are green-bar and blue-bar paper, and
# "plain" has no background on the paper, just the tractor feed holes.
#
# The "noskip" variants allow printing on each of the 66 printable lines per
# page; without "noskip" the profiles automatically skip the first 5 lines
# per page, as was a common forms control default for 1403 printers driven
# by JES2 so the first line of each page is the title line and the remaining
# lines are in the numbered portion of the page.
#
# If an unknown or empty profile is configured, "default-green" will be used.
#
#############################################################################
profile: "default-green"

### ADVANCED CONFIGURATION - MULTIPLE INPUTS/OUTPUTS ########################
#
# The agent is able to connect to more than one source (e.g. multiple copies
# of Hercules, or multiple sockdev printers on one copy of Hercules) and more
# than one output (e.g. different profiles in online more and/or different
# folders and profiles in local mode).
#
# You must always provide the input and output default configuration above
# in this configuration file. The information above will create both an
# input and output named "default".
#
# You may then define additional inputs and outputs in the following config
# sections. The additional inputs may be configured to go to the "default"
# output, or to another named output.
#
# The "inputs" and "outputs" structures are YAML arrays: the hyphen (-)
# before a member key begins a new entry in the array.
#
#############################################################################
#
#inputs:
#- name: "extra_in_1"
#  hercules_address: "127.0.0.1:1404"
#  output: "default"
#- name: "extra_in_2"
#  hercules_address: "another.system.example.com:1403"
#  output: "extra_out_local"
#
#outputs:
#- name: "extra_out_online"
#  mode: "online"
#  service_address: "https://1403.bitnet.systems/print"
#  access_key: "my-api-key-123"
#  profile: "retro-plain-noskip"
#- name: "extra_out_local"
#  mode: "local"
#  output_directory: "pdfs_2"
#  font_file: "my_font.ttf"
#  profile: "default-green"
